CREATE TABLE users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password_hash VARCHAR(255),
    rank VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

INSERT INTO users (username, password_hash, rank)
VALUES ('admin', '$2a$10$BQS3e/O41spfPbIeVh95kO5g6WKHO35bA6DPawiNmCw2YFWI66Zqa', 'ADMIN');