CREATE TABLE users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password_hash VARCHAR(255),
    rank VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

INSERT INTO users (username, password_hash, rank)
VALUES ('admin', '$2a$10$BQS3e/O41spfPbIeVh95kO5g6WKHO35bA6DPawiNmCw2YFWI66Zqa', 'ADMIN');

CREATE TABLE files
(
    id   BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255),
    type VARCHAR(255),
    data BLOB,
    CONSTRAINT pk_files PRIMARY KEY (id)
);

CREATE TABLE sauces
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    brand VARCHAR(255),
    desc  VARCHAR(255),
    CONSTRAINT pk_sauces PRIMARY KEY (id)
);